name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test_x86_x64:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Host properties
      run: lscpu

    - name: Configure CMake
      run: cmake ./prj/cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSIMD_TEST_FLAGS="-mavx2"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --parallel$(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./Test "-r=.." -m=a -tt=$(nproc) "-ot=log_${{matrix.build_type}}.txt"

  build_arm_cross:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Host properties
      run: lscpu

    - name: Install toolchain
      run: sudo apt-get -y install g++-arm-linux-gnueabihf

    - name: Configure CMake
      run: cmake ./prj/cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSIMD_TOOLCHAIN="arm-linux-gnueabihf-g++" -DSIMD_TARGET="arm"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --parallel$(nproc)

  build_aarch64_cross:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Host properties
      run: lscpu

    - name: Install toolchain
      run: sudo apt-get -y install g++-aarch64-linux-gnu

    - name: Configure CMake
      run: cmake ./prj/cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSIMD_TOOLCHAIN="aarch64-linux-gnu-g++" -DSIMD_TARGET="aarch64"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --parallel$(nproc)

  build_ppc64_cross:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Host properties
      run: lscpu

    - name: Install toolchain
      run: sudo apt-get -y install g++-powerpc-linux-gnu

    - name: Configure CMake
      run: cmake ./prj/cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSIMD_TOOLCHAIN="powerpc-linux-gnu-g++" -DSIMD_TARGET="ppc64"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --parallel$(nproc)

  build_and_test_clang:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Host properties
      run: lscpu

    - name: Install toolchain
      run: sudo apt-get -y install clang

    - name: Configure CMake
      run: cmake ./prj/cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSIMD_TOOLCHAIN="clang" -DSIMD_TARGET=""

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --parallel$(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./Test "-r=.." -m=a -tt=$(nproc) "-ot=log_${{matrix.build_type}}.txt"
